/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibUNEcW5WUjBNVmJoT2ZTSU50WEFtTFBmQk41WXkrTGQzN0I5UjBHYURYQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMW10NUJESWh3OFN5ODcrOEgxOEVvMW9UK3piY1g2ZnZyWlovSmtxS3ZWTT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBTmZYVW9PMWRudmVEaHRwUDlWQ2lVOVI0MDd3R1FMWDJZSjMxZWQrVTNJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJmVlhMSWtwYzlvem1LcVE2YVl2NFhuazFYNnMxc3BXZk5yaGlwZmRzaVZNPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InlIdU9zODh3ZDN6ckd6aUY0RzBPbzN2M1lVWUxENVFpQWRzb3FpSy9pVnM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1SdXQrbkJNTXBHS2NPVWNZTUtscnptMS9jODAvNGFEZy8zT2QxUTc2VzA9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYU44QnpMOG9jdVhZV1pXMWliaTJMbm9sMVBaWGFSVko4VVNQMW1HZGVrQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNmptcWg4aG5FTDlGQk9TSHVZa0xtazdkVDFJMmNaODlSS3RpQmFFcGZSUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZuM0k3bEZWMGdRN0k5MENpYVB5Z1g0SEJOeWYwRys4eSt4cnllMXZNaVl2Q0NzaEZZVWdSOWFoOEdqMFVIdmRpNXBuUVlDYnlTWFh0eU5DSUIxeENnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTAyLCJhZHZTZWNyZXRLZXkiOiIvV1UvMDZxZjZUMVRtOHNkUlg1YUxZL05uNkpBMTNNcTZUa005TXo4NUJNPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDExMzYzMTIzMkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJCNzQ0QzFBN0E3NjNDMTQ0MDY5NzE2RjQ5QUNFQjcyRiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMwNTI4MzM1fV0sIm5leHRQcmVLZXlJZCI6MzMsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMywiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJ4V3FJaHJiVVM1ZXAzcEdyRk5nYmh3IiwicGhvbmVJZCI6Ijk5YmZhMDVkLWY4YWEtNGNjNy1hM2MxLWJlYzQzZjI2NDA3NyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJZOWVLQmsvM3JRa2Y0dmxkU2pXY0lQQ201OFk9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidzBWVENtTlhGUXh4N3RrQlUzT1BJb3UycDBrPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IkdaMko1RlhXIiwibWUiOnsiaWQiOiIyNTQxMTM2MzEyMzI6MzBAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiSHVtcGhyZXkgVHV2YSBOZ2FsbGEifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0szSm51TUZFTFdJbDdrR0dBUWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IkZUYk45ZU9ydEhSZGJ0VjBCS3l0bnRJdVEzN0ttU3BsYm5JT2RkTFNyVVU9IiwiYWNjb3VudFNpZ25hdHVyZSI6IisvWE94SHFDMzduZUJUeml2YUEzMldiNUFUckJrbDJ6S0c1U1hoalRoN20vdC81aTlGdnQyeEx0SU9nSVpWd1dFeVJtSkNjZnBGNHF1bTFWMURPbkNnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJVb0NnazlKK0NWcGlFVXRjSnFubFBJdHovdFJXV0lMTnJkWkhSMlQwV2xWbW9NWHp1cnJmV3BldG1KTlZhbGVQTUhkck1vWi9qbXQzZU9IMXZjWURDdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDExMzYzMTIzMjozMEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJSVTJ6ZlhqcTdSMFhXN1ZkQVNzclo3U0xrTit5cGtxWlc1eURuWFMwcTFGIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMwNTI4MzIyLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU44diJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'fortunatus';
const packname = process.env.PACKNAME || 'dreaded md2 🤖';
const dev = process.env.DEV || '254114018035';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'DREADED';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
