/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMklJQUcyalY2YUtIc1d0RzEzdTZVZTNScFNITUhzOWxzS0k4SkpEdWhIOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibURuMHFDbHFPeFN6RHZkdHVoZTR4MjZoWWpXbDJHNFpxcWp0R0YxRWkyOD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJNTlpWNmlPQlcrTWxwWVgvemJpSzhpaDNQK29PTi9xY1d6Q0g1TENjbm5jPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFT1p1VU9TejJjMmdmK2wrWlV5bE0yVCtOQlVVd2c1U0xVZ25Edm9zUmdnPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFFbDBjRTZYR1g4N3F0VlRJbmdNekd1dlNOVjE5ZzdVSWxVTXhOSDRqbUU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklrVGpVNmlGM2lYbkxmajAxcXU0ajRKRnRlVHVNMGdTU3pUVmVFMVFaR009In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0xmRHhjREFwZ0lQSEtyeDVTNUh0RWVHay9idXdkN1VkYlIwdG1WOUxudz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK1JLT2hMWUpXdEtmK1BJeUZOZTNiRDg2c2xvVm9VYmZYTHZUQnk4VHR3dz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ijd0dm1FODdNRGJkU3RHOHI2em90TzBBS01IdW4wTnpxRnVoRGg0UU8vaXJqK3I0M0Q1VGp0OHl0Zk9scWlPRCtPZmJ4Q25pakhVNWVJUkdXR0REUmdnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjI2LCJhZHZTZWNyZXRLZXkiOiJ4QzM5aGw5ZnAzbWhGS0JZZHMrNnFIcTd3NEhaTnlYYk9xc1Y2M0NLUTJNPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI2Mzc3MTYwMDgxM0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJDOEYxQzMzMDU3QjVEMDc0MTJBRTdDMTk4RTdENkRDOCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzMwODMzNjQ3fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNjM3NzE2MDA4MTNAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiN0I3QUZDODk4QkQ4MTNFRTBBQjU1NThCODlBRUQ2NTgifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczMDgzMzY1MX1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiVnlneUMtalBRZGF5UTRRU0NsU2JEZyIsInBob25lSWQiOiJjYTk5NDkxYi02MmQ5LTRmOWMtODZhZC02ZWU2Yjc3ODJkNjQiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNlM2R241SlcxRzhxbjZMaTR4V09QOTAyZDdzPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImxkelpnTitTQVlwenRXOXV1bFUxYmhtVHI5TT0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJYNzFGWEM5WiIsIm1lIjp7ImlkIjoiMjYzNzcxNjAwODEzOjExQHMud2hhdHNhcHAubmV0IiwibmFtZSI6IuKaofCflKXwnZCS8J2Qk/CdkJHwnZCI8J2QivCdkITwnZCR8J2QgfCdkI7wnZCYyrfhtZLKs8uh4bWI4oed8J+UpeKaoSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDS2FqMTBnUXc5bXB1UVlZQlNBQUtBQT0iLCJhY2NvdW50U2lnbmF0dXJlS2V5Ijoicm5EMDRLSzlmZFJrZ1dUaVRLZzhpbDd0U0RJWkU1Ni95cEl3cG44aHNoMD0iLCJhY2NvdW50U2lnbmF0dXJlIjoiM0dUNXJCWnVHODJ0YTR6b1FxNlF0Q3pVRHp0cEJLZlRGQTBJRm5LcTBubjNubDl3L05KVnlSUG9hbWxkVUM2TWx2UzdqT2pxQmJReitSVWZuSXozQlE9PSIsImRldmljZVNpZ25hdHVyZSI6ImJOc1JHL2d0VGV0Ukw3UHdaUTErUkZ3Y3R4aHNoTlN1bnFvdGRWU1hMZU40cmtURjFIQWdTK3V1UWcxZXIrbVBRQ2NvNVJsN3ozTTM0Z3hVb3RGWWhRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjYzNzcxNjAwODEzOjExQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmE1dzlPQ2l2WDNVWklGazRreW9QSXBlN1VneUdST2V2OHFTTUtaL0liSWQifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzA4MzM2MTYsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBQ3dVIn0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'sᴛʀɪᴋᴇʀʙᴏʏ';
const packname = process.env.PACKNAME || 'strikerboy_bot';
const dev = process.env.DEV || '263771600813,263771110804,263719765023';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'sᴛʀɪᴋᴇʀʙᴏʏ_вσt';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';

const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
autolike,
  prefix,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
